theme: jekyll-theme-minimal
title:
logo: /assets/img/NHM_Logo_center.jpg
description: Official Github page test
show_downloads: true
sidebar:
  - title: "Title"
    image: "/assets/images/your-image.jpg"
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."
    nav: sidebar-sample
